### ISSUE TITLE
add parameter abreviations to file name of extracted data

### ISSUE THREAD

**Issue by baptischmi** [BirdScanCommunity/birdscanR#29]
Presently, the file is saved as: "dbName_DataExtract.rds"
File name could include additional standard metadata as only the database name. DOr instance, the extracted is based on several parameters, such as short-pulse, rotation, echo classes, time and altitude range.

**Comment by BirgenH** [comment]
The function extractDbData() does currently not include much filtering options anymore. It's mainly a simply extraction from the SQL database, so seems appropriate to keep a generic name. Filtering has been moved to filterData() which does not include a save file option anymore. Saving and naming of saved filtered dataset is now completely in hands of the user.
