### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [BirdScanCommunity/birdscanR#34]
maptools, rgeos and rgdal will be retiring as announced, in
October 2023, and your package uses sun-methods in maptools. 

You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023. 

Please collaborate with other users of sun methods ASAP.

**Comment by BirgenH** [comment]
Thanks @rsbivand for the heads up! I'll take care of it, in communication with other sun method dependent package maintainers also.

**Comment by rsbivand** [comment]
Only three months remain to save this package from failure. Please act now!

**Comment by rsbivand** [comment]
@BirgenH Less than three weeks remain to fix this.

**Comment by rsbivand** [comment]
Less than three weeks remain to fix this.
